### PR TITLE
Update search result highlighting

### PR DESCRIPTION
**Pull request by acdha**
This partially restores correct search result highlighting, along with some other code cleanup.

The logic was changed awhile back to use a prefix match in JavaScript which made it extremely noisy
for short prefixes (e.g. “major h. b. ferguson”  would match every word starting with h or b).

* https://github.com/LibraryOfCongress/chronam/commit/3b18aa0004761a5c656964e4f06be7041947b5c3
* https://github.com/LibraryOfCongress/chronam/commit/20a8cd8f59adbda3b9530e43faaead86a2d33dd8

This PR changes the logic to convert both terms to lower-case, trims punctuation and leading/trailing
whitespace, and then tests for exact matches so e.g. “h.” would match “H.”, “H”, “h!”, etc. but not “How” or “oh”. It also uses locale-aware lower-case transforms for non-English content and has a minor performance optimization. 

## Tasks
* [x] Fix matching code to only match words which are the same except for punctuation
* [x] Consolidate the three separate search highlighting implementations into a single file so matching  can be maintained and tested independently of the logic which displays the overlay
* [ ] Review the highlighting results — in testing, some highlights are placed over areas without text content

### CODE REVIEW

**Comment by acdha** [comment]
It's using [Prettier](https://prettier.io) so now you can just enable auto-formatting in most editors to have the CSS & JS be consistent.

**Comment by acdha** [comment]
@myusuf I took a first pass at consolidating the matching code. There's plenty of other cleanup which could be done but I'm not sure how much more the project warrants in its current state. I tried to flag all of the commits which are just white-space / syntax cleanup using Prettier so they can be ignored. There's also a bit of updates to the documentation as I updated the process of getting a working development site running.

https://github.com/LibraryOfCongress/chronam/pull/203/commits/b05ea4c7cc8d71f3dc590712f8deb6e6c6c86daa also sets `pointer-events: none` to avoid the problem where the highlight overlays were blocking mouse clicks if you happened to click on the overlay rather than the adjacent image.

**Comment by myusuf** [comment]
Looks good to me @acdha 
The PR still shows as WIP ( you may be aware of it)

**Comment by acdha** [comment]
I was waiting on some user testing first - I have the Ansible playbooks mostly fixed

**Pull request merged**
