### PR TITLE
CHARONAM-353 Show All Digitized Papers 1860-1922 (<number>) and Language select box should be populated with <number> and languages

### PR DESCRIPTION
**Pull request by lsukharn**
@myusuf @acdha @johnscancella 
CHARONAM-353 Show All Digitized Papers 1860-1922 (<number>)
and Language select box should be populated with <number>
and languages / Removed caching because: 1.Every time we have
to add a new batch we got to comment this line (`if info is None:`)
out 2. The amount of data that gets cached is small
enough to simply query the db

### CODE REVIEW

**Comment by acdha** [comment]
Does anyone have profiling data on this? i.e. how often is this called and how long it takes to run? If it's being called on pages which are cached, it might be worth the trouble, especially if the database queries are optimized — e.g. I see things like this where there's a lot of work being done in Python which looks like it could be delegated to the database:

```_places = models.
states_with_issues = sorted(set(place.state for place in _places if place.state is not None))
```
vs.
```
states_with_issues = State.objects.filter(place__in=Place.objects.filter(titles__in=titles_with_issues, state__isnull=False))
```

Similarly, the Ethnicities with issues check is doing queries in a loop when it could be using the ORM's annotation feature & filtering feature to do that in the original query so it never even has to process the rows which don't match.

(any time I see a query going into `set()` that's a good time to look for better use of the ORM. In a few cases with MySQL and large subqueries it might be slower to do that in the database but those should be relatively uncommon and documented)

**Comment by acdha** [comment]
On the rationale for this, why doesn't our deployment call `cache.delete()` or `cache.clear()` when it's ready? I think clearing the cache would make sense any time we ingest data.

https://docs.djangoproject.com/en/1.11/topics/cache/#the-low-level-cache-api

**Comment by johnscancella** [comment]
@acdha because we ingest on a different machine than we use to serve the http requests. so we would create a process to do the cache clearing across the firewall.

**Comment by acdha** [comment]
How automated is that process - is it human initiated or would we simply want, say, a scheduled task which checks the last load date in the database and clears the cache when it changes?

**Comment by johnscancella** [comment]
Right now the ingest on production is manually kicked off. So yeah we could have a cron job or something that purges the cache based on the database. But wouldn't we also need a process that clears the varnish cache and the cloudflare cache?

**Comment by acdha** [comment]
We already need to clear the other caches unless the timeouts are low enough that we just wait for them to expire. Since the ingest process is manual, would it make sense to have a `purge_cache` command which would purge the local (filesystem, memcached?) cache and the local Varnish instance? (CloudFlare is complicated since not everyone uses it)

Basically I see two points related to this change: one is simply reviewing the performance benefit from caching to decide whether it's worth it at all. The other is part of the larger process of reviewing the necessary update frequency, the cache TTLs for the cached components, etc. and deciding whether we want to change the TTLs or add a corresponding purge mechanism. In this case, it's also complicated by the fact that until https://github.com/LibraryOfCongress/chronam/commit/0945db2558d6363cee53fd1de4af50ac3580dce6 this particular bit of information was cached for IIRC 2 months so it might be worth asking how much we care now that it can be at most one day.

**Comment by acdha** [comment]
@johnscancella pointed out to me that this is a context processor, which seems like an area where we can improve performance simply by improving the design. The cache might be faster than a bunch of database queries but it's not free and a context processor really should be used only for things which are used by almost every request.

A quick search shows that `total_page_count` is used in exactly one page: the base template in the share tool block: 

https://github.com/LibraryOfCongress/chronam/search?utf8=%E2%9C%93&q=total_page_count&type=

I would move that into a template [`simple_tag`](https://docs.djangoproject.com/en/1.11/howto/custom-template-tags/#simple-tags) which can be used in that place and, if necessary, wrapped in a [`{% cache %}` block](https://docs.djangoproject.com/en/1.11/topics/cache/#template-fragment-caching).

All of the other values appear to be used in the tabs.html template which is referenced only by the tabs view:

https://github.com/LibraryOfCongress/chronam/blob/2111e4641f87f13a28de5c8114d7d400b2131766/core/views/home.py#L64

I would move those values into that view and apply the optimizations discussed above to reduce the total database load but since `/tabs` is cached for a day we'd be calling that a couple of times a day total rather than on every request as before.

**Pull request closed without merging**
